# Root variables: declare all inputs with types and descriptions
# Replace placeholders in terraform.tfvars

variable "subscription_id" {
  description = "Azure subscription ID"
  type        = string
  sensitive   = true
}

variable "tenant_id" {
  description = "Azure AD tenant ID"
  type        = string
  sensitive   = true
}

variable "resource_group_name" {
  description = "Resource group name for all resources"
  type        = string
}

variable "location" {
  description = "Azure region"
  type        = string
  default     = "eastus"
}

variable "vnet_name" {
  description = "Virtual network name"
  type        = string
  default     = "aro-vnet"
}

variable "vnet_address_space" {
  description = "VNet address space"
  type        = string
  default     = "10.0.0.0/16"
}

variable "control_subnet_prefix" {
  description = "Control plane subnet CIDR"
  type        = string
}

variable "worker_subnet_prefixes" {
  description = "List of worker subnet CIDRs"
  type        = list(string)
}

variable "cluster_name" {
  description = "ARO cluster name"
  type        = string
}

variable "domain" {
  description = "Custom domain for ARO cluster (leave empty for autogenerated)"
  type        = string
  default     = ""
}

variable "openshift_version" {
  description = "OpenShift version"
  type        = string
  default     = "4.12.25"
}

variable "pull_secret_path" {
  description = "Path to Red Hat pull secret file"
  type        = string
}

variable "master_vm_size" {
  description = "VM size for master nodes"
  type        = string
  default     = "Standard_D8s_v3"
}

variable "worker_vm_size" {
  description = "VM size for worker nodes"
  type        = string
  default     = "Standard_D4s_v3"
}

variable "worker_disk_size_gb" {
  description = "Disk size for worker nodes in GB"
  type        = number
  default     = 128
}

variable "worker_node_count" {
  description = "Number of worker nodes in default pool"
  type        = number
  default     = 3
}

variable "worker_node_count_per_pool" {
  description = "Number of worker nodes per machine pool in infra module"
  type        = number
  default     = 2
}

variable "sp_client_id" {
  description = "Service principal client ID for ARO"
  type        = string
  sensitive   = true
}

variable "sp_client_secret" {
  description = "Service principal client secret for ARO"
  type        = string
  sensitive   = true
}

variable "api_visibility" {
  description = "API server visibility (Public or Private)"
  type        = string
  default     = "Public"
}

variable "ingress_visibility" {
  description = "Ingress visibility (Public or Private)"
  type        = string
  default     = "Public"
}

variable "infra_vm_size" {
  description = "VM size for infra nodes"
  type        = string
  default     = "Standard_D4s_v3"
}

variable "infra_disk_size_gb" {
  description = "Disk size for infra nodes in GB"
  type        = number
  default     = 128
}

variable "infra_node_count" {
  description = "Number of infra nodes"
  type        = number
  default     = 3
}

variable "tags" {
  description = "Tags to apply to all resources"
  type        = map(string)
  default = {
    Environment = "Development"
    ManagedBy   = "Terraform"
  }
}

# Network subnet naming
variable "control_subnet_name" {
  description = "Name for control plane subnet"
  type        = string
  default     = "aro-control-subnet"
}

variable "worker_subnet_name_prefix" {
  description = "Prefix for worker subnet names"
  type        = string
  default     = "aro-worker-subnet"
}

variable "pod_cidr" {
  description = "Pod CIDR for ARO cluster"
  type        = string
  default     = "10.128.0.0/14"
}

variable "service_cidr" {
  description = "Service CIDR for ARO cluster"
  type        = string
  default     = "172.30.0.0/16"
}

# Storage Account Variables
variable "create_storage" {
  description = "Whether to create storage account"
  type        = bool
  default     = false
}

variable "storage_account_name" {
  description = "Storage account name (must be globally unique)"
  type        = string
  default     = ""
}

variable "account_tier" {
  description = "Storage account tier"
  type        = string
  default     = "Standard"
}

variable "replication_type" {
  description = "Storage account replication type"
  type        = string
  default     = "LRS"
}

variable "account_kind" {
  description = "Storage account kind"
  type        = string
  default     = "StorageV2"
}

variable "enable_versioning" {
  description = "Enable blob versioning"
  type        = bool
  default     = false
}

variable "enable_change_feed" {
  description = "Enable change feed"
  type        = bool
  default     = false
}

variable "enable_private_endpoint" {
  description = "Enable private endpoint for storage"
  type        = bool
  default     = false
}

variable "public_network_access" {
  description = "Allow public network access"
  type        = bool
  default     = true
}

variable "allowed_ip_ranges" {
  description = "Allowed IP ranges for storage account"
  type        = list(string)
  default     = []
}

variable "allowed_subnet_ids" {
  description = "Allowed subnet IDs for storage account"
  type        = list(string)
  default     = []
}

variable "private_endpoint_subnet_id" {
  description = "Subnet ID for private endpoint"
  type        = string
  default     = ""
}

# DNS Zone Variables
variable "create_dns_zone" {
  description = "Whether to create DNS zone"
  type        = bool
  default     = false
}

variable "dns_zone_name" {
  description = "DNS zone name"
  type        = string
  default     = ""
}

variable "ingress_ip" {
  description = "Ingress IP address for DNS A record"
  type        = string
  default     = ""
}

# Front Door Variables
variable "create_frontdoor" {
  description = "Whether to create Front Door"
  type        = bool
  default     = false
}

variable "frontdoor_name" {
  description = "Front Door name"
  type        = string
  default     = ""
}

variable "backend_address" {
  description = "Backend address for Front Door"
  type        = string
  default     = ""
}

variable "backend_host_header" {
  description = "Backend host header"
  type        = string
  default     = ""
}

variable "domain_resource_group_name" {
  description = "Resource group containing the DNS zone"
  type        = string
  default     = ""
}
